name: CMD-TUMWGS
channels:
    - bioconda
    - conda-forge
    - defaults

dependencies:
    - bioconda::picard=2.21.2
    - bioconda::samtools=1.9
    - bioconda::sambamba=0.7.0
    - bioconda::vcflib=1.0.0_rc2
    - bioconda::bcftools=1.9
    - bioconda::snpsift=4.3
    - bioconda::snpeff=4.3.1t
    - bioconda::tabix=0.2.6
    - bioconda::htslib=1.9
    - bioconda::bedtools=2.29.0
    - bioconda::vcftools=0.1.16
    - bioconda::perl-vcftools-vcf=0.1.16
    - bioconda::vt=2015.11.10
    - bioconda::manta=1.6.0
    - bioconda::pybigwig=0.3.17
    - bioconda::perl-app-cpanminus=1.7044
    - bioconda::freebayes=1.3.1
    - bioconda::vardict-java=1.7.0
    - bioconda::pindel=0.2.5b9
    - r-base
    - perl-gd
    - mscorefonts